Most of Tumble
tumble-for-kronox/Tumble-Android pull request #10
Opened 2024-08-30 08:40 UTC by SvenLindstrom

Still TODO:
Bookmark and search screen are pretty much finished.
Bookmark details sheet is missing color picker.
User Resources are still work in progress.
Settings screen is missing external connections.
Nav deep links are not setup.
SettingsViewModel is missing function implementation.
Bookmark Settings unable to delete schedule.
Notification implementation.

2024-08-31 10:47 UTC, adisve requested changes
Incredibly nice work and very good code. I like what you have done! There are some minor issues that I commented on that you could check out before I accept it.

2024-08-31 10:47 UTC, adisve commented on app/src/main/java/tumble/app/tumble/data/api/auth/AuthApiService.kt
> +    suspend fun loginUser(
When debugging/running the app, signing in does not work for a known user. Is this intended for now?

2024-08-31 10:47 UTC, adisve commented on app/src/main/java/tumble/app/tumble/presentation/viewmodels/SearchViewModel.kt
> +    fun search(query: MutableState<String>, selectedSchoolId: Int){
When searching for a known schedule, the tab loads and then goes back to default uni selection. Is this intended for now?

2024-08-31 10:47 UTC, adisve commented on app/src/main/java/tumble/app/tumble/presentation/viewmodels/SettingsViewModel.kt
> +    fun rescheduleNotifications(previousOffset: Int, newOffset: Int){
When changing the notification offset, the app crashes and can not be started again. Is this intended for now?

2024-09-09 14:20 UTC, SvenLindstrom commented on app/src/main/java/tumble/app/tumble/presentation/viewmodels/SearchViewModel.kt
> +    fun search(query: MutableState<String>, selectedSchoolId: Int){
This works when connected to the server running locally

2024-09-09 14:31 UTC, SvenLindstrom commented on app/src/main/java/tumble/app/tumble/presentation/viewmodels/SettingsViewModel.kt
> +    fun rescheduleNotifications(previousOffset: Int, newOffset: Int){
This has been fixed

2024-09-09 14:40 UTC, adisve approved these changes

2024-09-09 14:40 UTC, adisve commented
You are welcome to merge it

2024-09-09 16:24 UTC, merged